# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Off by One
tagline:          Programming for the rest of us
url:              http://blog.jedd-ahyoung.com/
paginate:         5
baseurl:          /
author:
  name:           Jedd Ahyoung
  url:            http://www.jedd-ahyoung.com
  email:          jedd-ahyoung@gmail.com

# Sass
sass:
  sass_dir:          _scss
  style:            :compressed

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/jedd-ahyoung/off-by-one
