# Dependencies
markdown:         redcarpet
highlighter:         true

# Permalinks
permalink:        pretty

# Setup
title:            Off by one
tagline:          Programming for the rest of us
## url:              http://blog.jedd-ahyoung.com
url:              http://jedd-ahyoung.github.io/
paginate:         1
baseurl:          /off-by-one/
author:
  name:           Jedd Ahyoung
  url:            http://www.jedd-ahyoung.com
  email:          jedd-ahyoung@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/jedd-ahyoung/off-by-one
